<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="FluentValidation" Version="11.11.0" />
      <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.11.0" />
      <PackageReference Include="MediatR" Version="13.1.0" />
    </ItemGroup>

    <ItemGroup>
      <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\AssetManagement\AssetManagement.Application\AssetManagement.Application.csproj" />
      <ProjectReference Include="..\..\ChangeLog\ChangeLog.Application\ChangeLog.Application.csproj" />
      <ProjectReference Include="..\..\ChangeLog\ChangeLog.Contract\ChangeLog.Contract.csproj" />
      <ProjectReference Include="..\TicketManagement.Contract\TicketManagement.Contract.csproj" />
      <ProjectReference Include="..\..\..\Tems.Common\Tems.Common.csproj" />
      <ProjectReference Include="..\..\UserManagement\UserManagement.Infrastructure\UserManagement.Infrastructure.csproj" />
    </ItemGroup>

</Project>
