<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\ChangeLog\ChangeLog.Contract\ChangeLog.Contract.csproj" />
      <PackageReference Include="MediatR" Version="13.1.0" />
    </ItemGroup>

</Project>
