// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using temsAPI.Data;

namespace temsAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210321201543_AddingJWTBlackList")]
    partial class AddingJWTBlackList
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EquipmentTicket", b =>
                {
                    b.Property<string>("EquipmentsId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TicketsId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("EquipmentsId", "TicketsId");

                    b.HasIndex("TicketsId");

                    b.ToTable("EquipmentTicket");
                });

            modelBuilder.Entity("EquipmentTypeProperty", b =>
                {
                    b.Property<string>("EquipmentTypesId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PropertiesId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("EquipmentTypesId", "PropertiesId");

                    b.HasIndex("PropertiesId");

                    b.ToTable("EquipmentTypeProperty");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("PersonnelPersonnelPosition", b =>
                {
                    b.Property<string>("PersonnelId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PositionsId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("PersonnelId", "PositionsId");

                    b.HasIndex("PositionsId");

                    b.ToTable("PersonnelPersonnelPosition");
                });

            modelBuilder.Entity("PersonnelTicket", b =>
                {
                    b.Property<string>("PersonnelId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TicketsId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("PersonnelId", "TicketsId");

                    b.HasIndex("TicketsId");

                    b.ToTable("PersonnelTicket");
                });

            modelBuilder.Entity("RoomRoomLabel", b =>
                {
                    b.Property<string>("LabelsId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoomsId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LabelsId", "RoomsId");

                    b.HasIndex("RoomsId");

                    b.ToTable("RoomRoomLabel");
                });

            modelBuilder.Entity("RoomTicket", b =>
                {
                    b.Property<string>("RoomsId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TicketsId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RoomsId", "TicketsId");

                    b.HasIndex("TicketsId");

                    b.ToTable("RoomTicket");
                });

            modelBuilder.Entity("TEMSUserTicket", b =>
                {
                    b.Property<string>("AssignedTicketsId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AssigneesId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("AssignedTicketsId", "AssigneesId");

                    b.HasIndex("AssigneesId");

                    b.ToTable("TEMSUserTicket");
                });

            modelBuilder.Entity("temsAPI.Data.Entities.CommunicationEntities.Announcement", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AuthorID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsArchieved")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorID");

                    b.HasIndex("DateCreated");

                    b.ToTable("Announcements");
                });

            modelBuilder.Entity("temsAPI.Data.Entities.CommunicationEntities.FrequentTicketProblem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Problem")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FrequentTicketProblems");
                });

            modelBuilder.Entity("temsAPI.Data.Entities.CommunicationEntities.Log", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("EquipmentID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsArchieved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsImportant")
                        .HasColumnType("bit");

                    b.Property<string>("LogTypeID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PersonnelID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoomID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentID");

                    b.HasIndex("LogTypeID");

                    b.HasIndex("PersonnelID");

                    b.HasIndex("RoomID");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("temsAPI.Data.Entities.CommunicationEntities.LogType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LogTypes");
                });

            modelBuilder.Entity("temsAPI.Data.Entities.CommunicationEntities.Ticket", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClosedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("DateClosed")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsArchieved")
                        .HasColumnType("bit");

                    b.Property<string>("LabelId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Problem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ClosedById");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LabelId");

                    b.HasIndex("StatusId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("temsAPI.Data.Entities.CommunicationEntities.ToDo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreatedByID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateClosed")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Urgent")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByID");

                    b.ToTable("ToDos");
                });

            modelBuilder.Entity("temsAPI.Data.Entities.EquipmentEntities.DataType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DataTypes");
                });

            modelBuilder.Entity("temsAPI.Data.Entities.EquipmentEntities.Equipment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EquipmentDefinitionID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDefect")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("ParentID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double?>("Price")
                        .HasColumnType("float");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RegisterDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RegisteredByID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TEMSID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentDefinitionID");

                    b.HasIndex("ParentID");

                    b.HasIndex("RegisteredByID");

                    b.HasIndex("SerialNumber");

                    b.HasIndex("TEMSID");

                    b.ToTable("Equipments");
                });

            modelBuilder.Entity("temsAPI.Data.Entities.EquipmentEntities.EquipmentAllocation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateAllocated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateReturned")
                        .HasColumnType("datetime2");

                    b.Property<string>("EquipmentID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsArchieved")
                        .HasColumnType("bit");

                    b.Property<string>("PersonnelID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoomID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentID");

                    b.HasIndex("PersonnelID");

                    b.HasIndex("RoomID");

                    b.ToTable("EquipmentAllocations");
                });

            modelBuilder.Entity("temsAPI.Data.Entities.EquipmentEntities.EquipmentDefinition", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EquipmentTypeID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Identifier")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsArchieved")
                        .HasColumnType("bit");

                    b.Property<string>("ParentID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentTypeID");

                    b.HasIndex("Identifier");

                    b.HasIndex("ParentID");

                    b.ToTable("EquipmentDefinitions");
                });

            modelBuilder.Entity("temsAPI.Data.Entities.EquipmentEntities.EquipmentSpecifications", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EquipmentDefinitionID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PropertyID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentDefinitionID");

                    b.HasIndex("PropertyID");

                    b.ToTable("EquipmentSpecifications");
                });

            modelBuilder.Entity("temsAPI.Data.Entities.EquipmentEntities.EquipmentType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsArchieved")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EquipmentTypes");
                });

            modelBuilder.Entity("temsAPI.Data.Entities.EquipmentEntities.EquipmentTypeKinship", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ChildEquipmentTypeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ParentEquipmentTypeId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ChildEquipmentTypeId");

                    b.HasIndex("ParentEquipmentTypeId");

                    b.ToTable("EquipmentTypeKinships");
                });

            modelBuilder.Entity("temsAPI.Data.Entities.EquipmentEntities.Property", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DataTypeID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Max")
                        .HasColumnType("int");

                    b.Property<int?>("Min")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Options")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Required")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DataTypeID");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("temsAPI.Data.Entities.EquipmentEntities.PropertyEquipmentTypeAssociation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PropertyID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TypeID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PropertyID");

                    b.HasIndex("TypeID");

                    b.ToTable("PropertyEquipmentTypeAssociations");
                });

            modelBuilder.Entity("temsAPI.Data.Entities.KeyEntities.Key", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Identifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsArchieved")
                        .HasColumnType("bit");

                    b.Property<string>("RoomId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("Keys");
                });

            modelBuilder.Entity("temsAPI.Data.Entities.KeyEntities.KeyAllocation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateAllocated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateReturned")
                        .HasColumnType("datetime2");

                    b.Property<string>("KeyID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PersonnelID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("KeyID");

                    b.HasIndex("PersonnelID");

                    b.ToTable("KeyAllocations");
                });

            modelBuilder.Entity("temsAPI.Data.Entities.LibraryEntities.LibraryFolder", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LibraryFolders");
                });

            modelBuilder.Entity("temsAPI.Data.Entities.LibraryEntities.LibraryItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ActualName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateUploaded")
                        .HasColumnType("datetime2");

                    b.Property<string>("DbPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Downloads")
                        .HasColumnType("int");

                    b.Property<double>("FileSize")
                        .HasColumnType("float");

                    b.Property<string>("LibraryFolderId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UploadedById")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("LibraryFolderId");

                    b.HasIndex("UploadedById");

                    b.ToTable("LibraryItems");
                });

            modelBuilder.Entity("temsAPI.Data.Entities.OtherEntities.Label", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Labels");
                });

            modelBuilder.Entity("temsAPI.Data.Entities.OtherEntities.Personnel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsArchieved")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TEMSUserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("TEMSUserId");

                    b.ToTable("Personnel");
                });

            modelBuilder.Entity("temsAPI.Data.Entities.OtherEntities.PersonnelPosition", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsArchieved")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PersonnelPositions");
                });

            modelBuilder.Entity("temsAPI.Data.Entities.OtherEntities.PersonnelRoomSupervisory", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("DateCanceled")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateSet")
                        .HasColumnType("datetime2");

                    b.Property<string>("PersonnelID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoomID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PersonnelID");

                    b.HasIndex("RoomID");

                    b.ToTable("PersonnelRoomSupervisories");
                });

            modelBuilder.Entity("temsAPI.Data.Entities.OtherEntities.Room", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Floor")
                        .HasColumnType("int");

                    b.Property<string>("Identifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsArchieved")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("temsAPI.Data.Entities.OtherEntities.RoomLabel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsArchieved")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RoomLabels");
                });

            modelBuilder.Entity("temsAPI.Data.Entities.OtherEntities.Status", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ImportanceIndex")
                        .HasColumnType("int");

                    b.Property<bool>("IsArchieved")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Statuses");
                });

            modelBuilder.Entity("temsAPI.Data.Entities.UserEntities.JWT", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("JWTBlacklist");
                });

            modelBuilder.Entity("temsAPI.Data.Entities.UserEntities.Privilege", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Identifier")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Privileges");
                });

            modelBuilder.Entity("temsAPI.Data.Entities.UserEntities.RolePrivileges", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PrivilegeID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PrivilegeID");

                    b.HasIndex("RoleID");

                    b.ToTable("RolePrivileges");
                });

            modelBuilder.Entity("temsAPI.Data.Entities.UserEntities.TEMSUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsArchieved")
                        .HasColumnType("bit");

                    b.Property<string>("PersonnelId")
                        .HasColumnType("nvarchar(450)");

                    b.HasIndex("PersonnelId");

                    b.HasDiscriminator().HasValue("TEMSUser");
                });

            modelBuilder.Entity("EquipmentTicket", b =>
                {
                    b.HasOne("temsAPI.Data.Entities.EquipmentEntities.Equipment", null)
                        .WithMany()
                        .HasForeignKey("EquipmentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("temsAPI.Data.Entities.CommunicationEntities.Ticket", null)
                        .WithMany()
                        .HasForeignKey("TicketsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EquipmentTypeProperty", b =>
                {
                    b.HasOne("temsAPI.Data.Entities.EquipmentEntities.EquipmentType", null)
                        .WithMany()
                        .HasForeignKey("EquipmentTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("temsAPI.Data.Entities.EquipmentEntities.Property", null)
                        .WithMany()
                        .HasForeignKey("PropertiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PersonnelPersonnelPosition", b =>
                {
                    b.HasOne("temsAPI.Data.Entities.OtherEntities.Personnel", null)
                        .WithMany()
                        .HasForeignKey("PersonnelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("temsAPI.Data.Entities.OtherEntities.PersonnelPosition", null)
                        .WithMany()
                        .HasForeignKey("PositionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PersonnelTicket", b =>
                {
                    b.HasOne("temsAPI.Data.Entities.OtherEntities.Personnel", null)
                        .WithMany()
                        .HasForeignKey("PersonnelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("temsAPI.Data.Entities.CommunicationEntities.Ticket", null)
                        .WithMany()
                        .HasForeignKey("TicketsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RoomRoomLabel", b =>
                {
                    b.HasOne("temsAPI.Data.Entities.OtherEntities.RoomLabel", null)
                        .WithMany()
                        .HasForeignKey("LabelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("temsAPI.Data.Entities.OtherEntities.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RoomTicket", b =>
                {
                    b.HasOne("temsAPI.Data.Entities.OtherEntities.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("temsAPI.Data.Entities.CommunicationEntities.Ticket", null)
                        .WithMany()
                        .HasForeignKey("TicketsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TEMSUserTicket", b =>
                {
                    b.HasOne("temsAPI.Data.Entities.CommunicationEntities.Ticket", null)
                        .WithMany()
                        .HasForeignKey("AssignedTicketsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("temsAPI.Data.Entities.UserEntities.TEMSUser", null)
                        .WithMany()
                        .HasForeignKey("AssigneesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("temsAPI.Data.Entities.CommunicationEntities.Announcement", b =>
                {
                    b.HasOne("temsAPI.Data.Entities.UserEntities.TEMSUser", "Author")
                        .WithMany("Announcements")
                        .HasForeignKey("AuthorID");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("temsAPI.Data.Entities.CommunicationEntities.Log", b =>
                {
                    b.HasOne("temsAPI.Data.Entities.EquipmentEntities.Equipment", "Equipment")
                        .WithMany("Logs")
                        .HasForeignKey("EquipmentID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("temsAPI.Data.Entities.CommunicationEntities.LogType", "LogType")
                        .WithMany("Logs")
                        .HasForeignKey("LogTypeID");

                    b.HasOne("temsAPI.Data.Entities.OtherEntities.Personnel", "Personnel")
                        .WithMany("Logs")
                        .HasForeignKey("PersonnelID");

                    b.HasOne("temsAPI.Data.Entities.OtherEntities.Room", "Room")
                        .WithMany("Logs")
                        .HasForeignKey("RoomID");

                    b.Navigation("Equipment");

                    b.Navigation("LogType");

                    b.Navigation("Personnel");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("temsAPI.Data.Entities.CommunicationEntities.Ticket", b =>
                {
                    b.HasOne("temsAPI.Data.Entities.UserEntities.TEMSUser", "ClosedBy")
                        .WithMany("ClosedTickets")
                        .HasForeignKey("ClosedById");

                    b.HasOne("temsAPI.Data.Entities.UserEntities.TEMSUser", "CreatedBy")
                        .WithMany("CreatedTickets")
                        .HasForeignKey("CreatedById");

                    b.HasOne("temsAPI.Data.Entities.OtherEntities.Label", "Label")
                        .WithMany("Tickets")
                        .HasForeignKey("LabelId");

                    b.HasOne("temsAPI.Data.Entities.OtherEntities.Status", "Status")
                        .WithMany("Tickets")
                        .HasForeignKey("StatusId");

                    b.Navigation("ClosedBy");

                    b.Navigation("CreatedBy");

                    b.Navigation("Label");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("temsAPI.Data.Entities.CommunicationEntities.ToDo", b =>
                {
                    b.HasOne("temsAPI.Data.Entities.UserEntities.TEMSUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByID");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("temsAPI.Data.Entities.EquipmentEntities.Equipment", b =>
                {
                    b.HasOne("temsAPI.Data.Entities.EquipmentEntities.EquipmentDefinition", "EquipmentDefinition")
                        .WithMany()
                        .HasForeignKey("EquipmentDefinitionID");

                    b.HasOne("temsAPI.Data.Entities.EquipmentEntities.Equipment", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentID")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("temsAPI.Data.Entities.UserEntities.TEMSUser", "RegisteredBy")
                        .WithMany("RegisteredEquipments")
                        .HasForeignKey("RegisteredByID");

                    b.Navigation("EquipmentDefinition");

                    b.Navigation("Parent");

                    b.Navigation("RegisteredBy");
                });

            modelBuilder.Entity("temsAPI.Data.Entities.EquipmentEntities.EquipmentAllocation", b =>
                {
                    b.HasOne("temsAPI.Data.Entities.EquipmentEntities.Equipment", "Equipment")
                        .WithMany("EquipmentAllocations")
                        .HasForeignKey("EquipmentID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("temsAPI.Data.Entities.OtherEntities.Personnel", "Personnel")
                        .WithMany("EquipmentAllocations")
                        .HasForeignKey("PersonnelID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("temsAPI.Data.Entities.OtherEntities.Room", "Room")
                        .WithMany("EquipmentAllocations")
                        .HasForeignKey("RoomID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Equipment");

                    b.Navigation("Personnel");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("temsAPI.Data.Entities.EquipmentEntities.EquipmentDefinition", b =>
                {
                    b.HasOne("temsAPI.Data.Entities.EquipmentEntities.EquipmentType", "EquipmentType")
                        .WithMany("EquipmentDefinitions")
                        .HasForeignKey("EquipmentTypeID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("temsAPI.Data.Entities.EquipmentEntities.EquipmentDefinition", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentID")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.Navigation("EquipmentType");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("temsAPI.Data.Entities.EquipmentEntities.EquipmentSpecifications", b =>
                {
                    b.HasOne("temsAPI.Data.Entities.EquipmentEntities.EquipmentDefinition", "EquipmentDefinition")
                        .WithMany("EquipmentSpecifications")
                        .HasForeignKey("EquipmentDefinitionID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("temsAPI.Data.Entities.EquipmentEntities.Property", "Property")
                        .WithMany("EquipmentSpecifications")
                        .HasForeignKey("PropertyID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("EquipmentDefinition");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("temsAPI.Data.Entities.EquipmentEntities.EquipmentTypeKinship", b =>
                {
                    b.HasOne("temsAPI.Data.Entities.EquipmentEntities.EquipmentType", "ChildEquipmentType")
                        .WithMany()
                        .HasForeignKey("ChildEquipmentTypeId");

                    b.HasOne("temsAPI.Data.Entities.EquipmentEntities.EquipmentType", "ParentEquipmentType")
                        .WithMany("EquipmentTypeKinships")
                        .HasForeignKey("ParentEquipmentTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ChildEquipmentType");

                    b.Navigation("ParentEquipmentType");
                });

            modelBuilder.Entity("temsAPI.Data.Entities.EquipmentEntities.Property", b =>
                {
                    b.HasOne("temsAPI.Data.Entities.EquipmentEntities.DataType", "DataType")
                        .WithMany("DataTypeProperties")
                        .HasForeignKey("DataTypeID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("DataType");
                });

            modelBuilder.Entity("temsAPI.Data.Entities.EquipmentEntities.PropertyEquipmentTypeAssociation", b =>
                {
                    b.HasOne("temsAPI.Data.Entities.EquipmentEntities.Property", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyID");

                    b.HasOne("temsAPI.Data.Entities.EquipmentEntities.EquipmentType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeID");

                    b.Navigation("Property");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("temsAPI.Data.Entities.KeyEntities.Key", b =>
                {
                    b.HasOne("temsAPI.Data.Entities.OtherEntities.Room", "Room")
                        .WithMany("Keys")
                        .HasForeignKey("RoomId");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("temsAPI.Data.Entities.KeyEntities.KeyAllocation", b =>
                {
                    b.HasOne("temsAPI.Data.Entities.KeyEntities.Key", "Key")
                        .WithMany("KeyAllocations")
                        .HasForeignKey("KeyID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("temsAPI.Data.Entities.OtherEntities.Personnel", "Personnel")
                        .WithMany("KeyAllocations")
                        .HasForeignKey("PersonnelID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Key");

                    b.Navigation("Personnel");
                });

            modelBuilder.Entity("temsAPI.Data.Entities.LibraryEntities.LibraryItem", b =>
                {
                    b.HasOne("temsAPI.Data.Entities.LibraryEntities.LibraryFolder", "LibraryFolder")
                        .WithMany()
                        .HasForeignKey("LibraryFolderId");

                    b.HasOne("temsAPI.Data.Entities.UserEntities.TEMSUser", "UploadedBy")
                        .WithMany()
                        .HasForeignKey("UploadedById");

                    b.Navigation("LibraryFolder");

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("temsAPI.Data.Entities.OtherEntities.Personnel", b =>
                {
                    b.HasOne("temsAPI.Data.Entities.UserEntities.TEMSUser", "TEMSUser")
                        .WithMany()
                        .HasForeignKey("TEMSUserId");

                    b.Navigation("TEMSUser");
                });

            modelBuilder.Entity("temsAPI.Data.Entities.OtherEntities.PersonnelRoomSupervisory", b =>
                {
                    b.HasOne("temsAPI.Data.Entities.OtherEntities.Personnel", "Personnel")
                        .WithMany("PersonnelRoomSupervisories")
                        .HasForeignKey("PersonnelID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("temsAPI.Data.Entities.OtherEntities.Room", "Room")
                        .WithMany("PersonnelRoomSupervisories")
                        .HasForeignKey("RoomID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Personnel");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("temsAPI.Data.Entities.UserEntities.RolePrivileges", b =>
                {
                    b.HasOne("temsAPI.Data.Entities.UserEntities.Privilege", "Privilege")
                        .WithMany()
                        .HasForeignKey("PrivilegeID");

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleID");

                    b.Navigation("Privilege");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("temsAPI.Data.Entities.UserEntities.TEMSUser", b =>
                {
                    b.HasOne("temsAPI.Data.Entities.OtherEntities.Personnel", "Personnel")
                        .WithMany()
                        .HasForeignKey("PersonnelId");

                    b.Navigation("Personnel");
                });

            modelBuilder.Entity("temsAPI.Data.Entities.CommunicationEntities.LogType", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("temsAPI.Data.Entities.EquipmentEntities.DataType", b =>
                {
                    b.Navigation("DataTypeProperties");
                });

            modelBuilder.Entity("temsAPI.Data.Entities.EquipmentEntities.Equipment", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("EquipmentAllocations");

                    b.Navigation("Logs");
                });

            modelBuilder.Entity("temsAPI.Data.Entities.EquipmentEntities.EquipmentDefinition", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("EquipmentSpecifications");
                });

            modelBuilder.Entity("temsAPI.Data.Entities.EquipmentEntities.EquipmentType", b =>
                {
                    b.Navigation("EquipmentDefinitions");

                    b.Navigation("EquipmentTypeKinships");
                });

            modelBuilder.Entity("temsAPI.Data.Entities.EquipmentEntities.Property", b =>
                {
                    b.Navigation("EquipmentSpecifications");
                });

            modelBuilder.Entity("temsAPI.Data.Entities.KeyEntities.Key", b =>
                {
                    b.Navigation("KeyAllocations");
                });

            modelBuilder.Entity("temsAPI.Data.Entities.OtherEntities.Label", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("temsAPI.Data.Entities.OtherEntities.Personnel", b =>
                {
                    b.Navigation("EquipmentAllocations");

                    b.Navigation("KeyAllocations");

                    b.Navigation("Logs");

                    b.Navigation("PersonnelRoomSupervisories");
                });

            modelBuilder.Entity("temsAPI.Data.Entities.OtherEntities.Room", b =>
                {
                    b.Navigation("EquipmentAllocations");

                    b.Navigation("Keys");

                    b.Navigation("Logs");

                    b.Navigation("PersonnelRoomSupervisories");
                });

            modelBuilder.Entity("temsAPI.Data.Entities.OtherEntities.Status", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("temsAPI.Data.Entities.UserEntities.TEMSUser", b =>
                {
                    b.Navigation("Announcements");

                    b.Navigation("ClosedTickets");

                    b.Navigation("CreatedTickets");

                    b.Navigation("RegisteredEquipments");
                });
#pragma warning restore 612, 618
        }
    }
}
